title:              Aerobotics
email:              aeroboticsftc@gmail.com
description:        FIRST Tech Challenge Team
author:             Aerobotics team
baseurl:            "/Aerobotics"
url:                "https://aeroboticsftc.github.io"

# Social Profiles
twitter_username:  
github_username:    aeroboticsftc
facebook_username:  aerobotics
instagram_username:  aerobotics.ftc
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
